'use client';
import {useState} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {ArrowUpRight,ChevronDown,TrendingUp,Wallet,MapPin} from 'lucide-react';
export type Fact={value:string;basis:string;source:string};
export type Comparison=Record<string,Fact>;
export type Job={title:string;url:string;location:string;fit:string;evidence:string;gaps:string;comparison?:Comparison;jdSnapshot?:string;applicationUrl?:string};
const labels:Record<string,string>={official:'官方信息',platform:'平台信息',sample:'个人样本',inference:'分析判断',unknown:'待确认'};
const rows=[['salary','起薪与总包'],['salaryReference','历史薪资参考'],['salaryGrowth','3–5年薪资空间'],['promotion','晋升路径'],['skills','专业与管理复利'],['transferability','技能可迁移性'],['industry','行业 / 赛道'],['growthCost','成长代价'],['workLife','工作生活平衡'],['mobility','国际流动'],['competitiveness','竞争力 / 录用难点']];
function FactView({fact}:{fact?:Fact}){return <div className="fact"><p>{fact?.value||'本轮尚未核实'}</p><span className={`basis ${fact?.basis||'unknown'}`}>{labels[fact?.basis||'unknown']}</span>{fact?.source?.startsWith('https://')&&<a href={fact.source} target="_blank" rel="noreferrer">依据 ↗</a>}</div>}
export function JobComparison({jobs,busy,onResume,tentative=false}:{jobs:Job[];busy:boolean;onResume:(job:Job)=>void;tentative?:boolean}){
 const [mode,setMode]=useState<'overview'|'growth'>('overview');
 if(!jobs.length)return null;
 const cols=mode==='overview'?[['salary','薪资'],['promotion','成长与晋升'],['workLife','工作生活平衡'],['mobility','国际流动']]:[['salaryGrowth','3–5年薪资空间'],['skills','能力复利'],['transferability','迁移性'],['growthCost','成长代价']];
 return <section className="comparison-section"><div className="comparison-title"><div><span className="eyebrow">COMPARE YOUR OPTIONS</span><h3>机会，放在一起看。</h3>{tentative&&<p>已核对的官网候选岗位；投递次数待官方规则确认，排序仅供初筛。</p>}</div><div className="view-switch"><button aria-pressed={mode==='overview'} onClick={()=>setMode('overview')}><Wallet size={16}/>综合比较</button><button aria-pressed={mode==='growth'} onClick={()=>setMode('growth')}><TrendingUp size={16}/>成长性细看</button></div></div>
 <div className="comparison-table"><Table><TableHeader><TableRow><TableHead>候选岗位 / 地点</TableHead>{cols.map(([k,label])=><TableHead key={k}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{jobs.map((p,i)=><TableRow key={p.url}><TableCell><a className="table-role" href={`#job-${i}`}><span className="rank">{String(i+1).padStart(2,'0')}</span>{p.title.replace(/-2027届/g,'')}</a><p className="place"><MapPin size={13}/>{p.location}</p></TableCell>{cols.map(([k])=><TableCell key={k}><FactView fact={p.comparison?.[k]}/>{k==='salary'&&p.comparison?.salaryReference?.basis!=='unknown'&&<div className="historical-salary"><FactView fact={p.comparison?.salaryReference}/></div>}</TableCell>)}</TableRow>)}</TableBody></Table></div>
 <div className="detail-heading"><h3>逐岗判断</h3><span>适配依据 · 取舍 · 下一步</span></div><div className="job-grid">{jobs.map((p,i)=><article id={`job-${i}`} key={p.url} className="job-card"><div className="job-top"><span className="job-number">{String(i+1).padStart(2,'0')}</span><span className="job-kind">{tentative?'待定候选':i<3?'优先考虑':'备选机会'}</span><a href={p.url} target="_blank" rel="noreferrer" aria-label={`打开 ${p.title} 官网详情`}>官网详情 <ArrowUpRight size={16}/></a></div><h4>{p.title.replace(/-2027届/g,'')}</h4><p className="place"><MapPin size={14}/>{p.location}</p><div className="salary-strip"><Wallet size={17}/><FactView fact={p.comparison?.salary}/></div><p className="job-fit">{p.fit}</p><details className="dimension-details"><summary>全部 11 项比较维度 <ChevronDown size={16}/></summary><dl>{rows.map(([k,name])=><div key={k}><dt>{name}</dt><dd><FactView fact={p.comparison?.[k]}/></dd></div>)}</dl></details><div className="job-gap"><strong>投递前补足</strong><p>{p.gaps}</p></div><details className="job-proof"><summary>岗位核验依据</summary><p>{p.evidence}</p></details>{p.jdSnapshot&&<details className="job-proof"><summary>查看本次官网 JD 快照</summary><p>{p.jdSnapshot}</p></details>}<div className="job-actions"><Button disabled={busy} onClick={()=>onResume(p)}>定制这份简历</Button>{p.applicationUrl&&p.applicationUrl!==p.url&&<a href={p.applicationUrl} target="_blank" rel="noreferrer">网申原始入口 ↗</a>}</div></article>)}</div></section>;
}
